### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by zeshengchen** [ChiragBellara/Video-Translation-Using-Deep-Learning#1]
Please do not put the slides under the root directory. Instead, please put it under "requirements" folder!

Moreover, as we discussed in the class, please do not commit the code or the files directly into the main branch. Instead, please create the pull request, invite other group member to peer review the code, and after getting all approval, complete the pull request!

**Comment by ChiragBellara** [comment]
Because this was a requirements file, a pull request was not created. I thought that the pull request pattern was to be followed for code only. Now a pull request has been created for adding the requirements file to the 'Requirements' folder.

**Comment by zeshengchen** [comment]
Please remove the slides file currently under the root directory in main branch!

**Comment by ChiragBellara** [comment]
Done. It was a part of the pull request. Removing the file from root and adding it to the Requirements folder.
